/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AccountWhereUniqueInput } from "../../account/base/AccountWhereUniqueInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
  IsNumber,
  Min,
  Max,
} from "class-validator";
import { Type } from "class-transformer";
import { MarketplaceSyncUpdateManyWithoutProductsInput } from "./MarketplaceSyncUpdateManyWithoutProductsInput";
import { OfferCardUpdateManyWithoutProductsInput } from "./OfferCardUpdateManyWithoutProductsInput";

@InputType()
class ProductUpdateInput {
  @ApiProperty({
    required: false,
    type: () => AccountWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AccountWhereUniqueInput)
  @IsOptional()
  @Field(() => AccountWhereUniqueInput, {
    nullable: true,
  })
  account?: AccountWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  imageUrl?: string | null;

  @ApiProperty({
    required: false,
    type: () => MarketplaceSyncUpdateManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => MarketplaceSyncUpdateManyWithoutProductsInput)
  @IsOptional()
  @Field(() => MarketplaceSyncUpdateManyWithoutProductsInput, {
    nullable: true,
  })
  marketplaceSyncs?: MarketplaceSyncUpdateManyWithoutProductsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => OfferCardUpdateManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => OfferCardUpdateManyWithoutProductsInput)
  @IsOptional()
  @Field(() => OfferCardUpdateManyWithoutProductsInput, {
    nullable: true,
  })
  offerCards?: OfferCardUpdateManyWithoutProductsInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  price?: number | null;
}

export { ProductUpdateInput as ProductUpdateInput };
