/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ProductService } from "../product.service";
import { ProductCreateInput } from "./ProductCreateInput";
import { Product } from "./Product";
import { ProductFindManyArgs } from "./ProductFindManyArgs";
import { ProductWhereUniqueInput } from "./ProductWhereUniqueInput";
import { ProductUpdateInput } from "./ProductUpdateInput";
import { MarketplaceSyncFindManyArgs } from "../../marketplaceSync/base/MarketplaceSyncFindManyArgs";
import { MarketplaceSync } from "../../marketplaceSync/base/MarketplaceSync";
import { MarketplaceSyncWhereUniqueInput } from "../../marketplaceSync/base/MarketplaceSyncWhereUniqueInput";
import { OfferCardFindManyArgs } from "../../offerCard/base/OfferCardFindManyArgs";
import { OfferCard } from "../../offerCard/base/OfferCard";
import { OfferCardWhereUniqueInput } from "../../offerCard/base/OfferCardWhereUniqueInput";

export class ProductControllerBase {
  constructor(protected readonly service: ProductService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Product })
  async createProduct(
    @common.Body() data: ProductCreateInput
  ): Promise<Product> {
    return await this.service.createProduct({
      data: {
        ...data,

        account: data.account
          ? {
              connect: data.account,
            }
          : undefined,
      },
      select: {
        account: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        description: true,
        id: true,
        imageUrl: true,
        name: true,
        price: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Product] })
  @ApiNestedQuery(ProductFindManyArgs)
  async products(@common.Req() request: Request): Promise<Product[]> {
    const args = plainToClass(ProductFindManyArgs, request.query);
    return this.service.products({
      ...args,
      select: {
        account: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        description: true,
        id: true,
        imageUrl: true,
        name: true,
        price: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Product })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async product(
    @common.Param() params: ProductWhereUniqueInput
  ): Promise<Product | null> {
    const result = await this.service.product({
      where: params,
      select: {
        account: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        description: true,
        id: true,
        imageUrl: true,
        name: true,
        price: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Product })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateProduct(
    @common.Param() params: ProductWhereUniqueInput,
    @common.Body() data: ProductUpdateInput
  ): Promise<Product | null> {
    try {
      return await this.service.updateProduct({
        where: params,
        data: {
          ...data,

          account: data.account
            ? {
                connect: data.account,
              }
            : undefined,
        },
        select: {
          account: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          description: true,
          id: true,
          imageUrl: true,
          name: true,
          price: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Product })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteProduct(
    @common.Param() params: ProductWhereUniqueInput
  ): Promise<Product | null> {
    try {
      return await this.service.deleteProduct({
        where: params,
        select: {
          account: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          description: true,
          id: true,
          imageUrl: true,
          name: true,
          price: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/marketplaceSyncs")
  @ApiNestedQuery(MarketplaceSyncFindManyArgs)
  async findMarketplaceSyncs(
    @common.Req() request: Request,
    @common.Param() params: ProductWhereUniqueInput
  ): Promise<MarketplaceSync[]> {
    const query = plainToClass(MarketplaceSyncFindManyArgs, request.query);
    const results = await this.service.findMarketplaceSyncs(params.id, {
      ...query,
      select: {
        createdAt: true,
        externalId: true,
        id: true,

        marketplace: {
          select: {
            id: true,
          },
        },

        product: {
          select: {
            id: true,
          },
        },

        status: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/marketplaceSyncs")
  async connectMarketplaceSyncs(
    @common.Param() params: ProductWhereUniqueInput,
    @common.Body() body: MarketplaceSyncWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      marketplaceSyncs: {
        connect: body,
      },
    };
    await this.service.updateProduct({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/marketplaceSyncs")
  async updateMarketplaceSyncs(
    @common.Param() params: ProductWhereUniqueInput,
    @common.Body() body: MarketplaceSyncWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      marketplaceSyncs: {
        set: body,
      },
    };
    await this.service.updateProduct({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/marketplaceSyncs")
  async disconnectMarketplaceSyncs(
    @common.Param() params: ProductWhereUniqueInput,
    @common.Body() body: MarketplaceSyncWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      marketplaceSyncs: {
        disconnect: body,
      },
    };
    await this.service.updateProduct({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/offerCards")
  @ApiNestedQuery(OfferCardFindManyArgs)
  async findOfferCards(
    @common.Req() request: Request,
    @common.Param() params: ProductWhereUniqueInput
  ): Promise<OfferCard[]> {
    const query = plainToClass(OfferCardFindManyArgs, request.query);
    const results = await this.service.findOfferCards(params.id, {
      ...query,
      select: {
        createdAt: true,
        description: true,
        id: true,
        imageUrl: true,
        name: true,
        price: true,

        product: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/offerCards")
  async connectOfferCards(
    @common.Param() params: ProductWhereUniqueInput,
    @common.Body() body: OfferCardWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      offerCards: {
        connect: body,
      },
    };
    await this.service.updateProduct({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/offerCards")
  async updateOfferCards(
    @common.Param() params: ProductWhereUniqueInput,
    @common.Body() body: OfferCardWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      offerCards: {
        set: body,
      },
    };
    await this.service.updateProduct({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/offerCards")
  async disconnectOfferCards(
    @common.Param() params: ProductWhereUniqueInput,
    @common.Body() body: OfferCardWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      offerCards: {
        disconnect: body,
      },
    };
    await this.service.updateProduct({
      where: params,
      data,
      select: { id: true },
    });
  }
}
